"""
Wald-Wolfowitz Runs Test for Randomness

Tests whether a binary sequence is randomly generated by counting
the number of "runs" (consecutive identical values) and comparing
to the expected distribution under independence.
"""

import argparse
import numpy as np
import scipy.stats as stats


def runs_test(data):
    """
    Wald-Wolfowitz runs test.

    Parameters
    ----------
    data : array-like
        A sequence of +1 and -1 values.

    Returns
    -------
    statistic : float
        The standardized Z statistic.
    p_value : float
        Two-sided p-value from normal approximation.
    """
    data = np.asarray(data)
    N = data.shape[0]
    N_plus = (data == 1).sum()
    N_minus = N - N_plus

    mu = 2 * N_plus * N_minus / N + 1
    sigma = np.sqrt((mu - 1) * (mu - 2) / (N - 1))
    R = (N_plus + N_minus + 1 - np.sum(data[1:] * data[:-1])) / 2

    statistic = (R - mu) / sigma
    p_value = 2 * stats.norm().cdf(-abs(statistic))

    return statistic, p_value


def interpret_result(statistic, p_value, alpha=0.05):
    print(f"{statistic = :.4f}")
    print(f"{p_value   = :.4f}")
    if p_value < alpha:
        print("→ Reject H₀: samples are not independently drawn", end="\n\n")
    else:
        print("→ Fail to reject H₀: samples are independently drawn", end="\n\n")


def main():
    parser = argparse.ArgumentParser(description="Runs Test for Randomness")
    parser.add_argument("--seed", type=int, default=1, help="random seed")
    parser.add_argument("--p", type=float, default=0.4, help="binomial probability")
    parser.add_argument("--size", type=int, default=200, help="sample size for random data")
    args = parser.parse_args()
    np.random.seed(args.seed)

    # Example 1: Clustered data (should reject randomness)
    print("=== Example 1: Clustered sequence ===")
    data = np.array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
    statistic, p_value = runs_test(data * 2 - 1)
    interpret_result(statistic, p_value)

    # Example 2: Well-mixed data (should not reject)
    print("=== Example 2: Well-mixed sequence ===")
    data = np.array([1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0])
    statistic, p_value = runs_test(data * 2 - 1)
    interpret_result(statistic, p_value)

    # Example 3: Random binomial data
    print(f"=== Example 3: Random Binomial(1, p={args.p}), n={args.size} ===")
    data = np.random.binomial(n=1, p=args.p, size=(args.size,))
    statistic, p_value = runs_test(data * 2 - 1)
    interpret_result(statistic, p_value)


if __name__ == "__main__":
    main()
